name: Tic Tac Toe CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Qt environment
        run: |
          sudo apt-get update
          sudo apt-get install -y qt5-qmake qtbase5-dev qt5-default

      - name: Build game
        run: |
          qmake -v
          qmake CONFIG+=debug
          make

      - name: Run unit tests
        run: ./tests/run_tests  # Replace with your test executable path

      - name: Analyze code quality
        run: |
          # Add any code quality analysis tools here (e.g., Clang static analyzer, cppcheck)

      - name: Package artifacts
        run: |
          # Package your built artifacts for deployment (if applicable)
          # For Qt projects, this might involve creating an installer or packaging the executable

      # Add deployment step if you have a deployment target like GitHub Pages, AWS, etc.
      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_dir: ./docs  # Replace with your build output directory
      #     publish_branch: gh-pages  # Replace with your deployment branch
